CREATE DATABASE PHARMA;

-- use python for data uploading 

USE PHARMA;


CREATE TABLE DIM_PRODUCT AS
SELECT
    ROW_NUMBER() OVER (ORDER BY PRODUCT_NAME) AS PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_CLASS
FROM (
    SELECT DISTINCT
        PRODUCT_NAME,
        PRODUCT_CLASS
    FROM MASTER_TABLE
) T;


CREATE TABLE DIM_CUSTOMER AS
SELECT
    ROW_NUMBER() OVER (ORDER BY CUSTOMER_NAME) AS CUSTOMER_ID,
    CUSTOMER_NAME,
    DISTRIBUTOR
FROM (
    SELECT DISTINCT
        CUSTOMER_NAME,
        DISTRIBUTOR
    FROM MASTER_TABLE
) T;


CREATE TABLE DIM_GEOGRAPHY AS
SELECT
    ROW_NUMBER() OVER (ORDER BY CITY, COUNTRY) AS GEO_ID,
    CITY,
    COUNTRY,
    LATITUDE,
    LONGITUDE
FROM (
    SELECT DISTINCT
        CITY,
        COUNTRY,
        LATITUDE,
        LONGITUDE
    FROM MASTER_TABLE
) T;


CREATE TABLE DIM_SALES_REP AS
SELECT
    ROW_NUMBER() OVER (ORDER BY NAME_OF_SALES_REP) AS SALES_REP_ID,
    NAME_OF_SALES_REP AS SALES_REP_NAME,
    MANAGER,
    SALES_TEAM
FROM (
    SELECT DISTINCT
        NAME_OF_SALES_REP,
        MANAGER,
        SALES_TEAM
    FROM MASTER_TABLE
) T;


CREATE TABLE DIM_CHANNEL AS
SELECT
    ROW_NUMBER() OVER (ORDER BY CHANNEL, SUB_CHANNEL) AS CHANNEL_ID,
    CHANNEL,
    SUB_CHANNEL
FROM (
    SELECT DISTINCT
        CHANNEL,
        SUB_CHANNEL
    FROM MASTER_TABLE
) T;


CREATE TABLE FACT_SALES_TRANSACTIONS AS
SELECT
    M.TXN_ID,
    M.DATE,
    P.PRODUCT_ID,
    C.CUSTOMER_ID,
    G.GEO_ID,
    R.SALES_REP_ID,
    CH.CHANNEL_ID,
    M.QUANTITY,
    M.PRICE,
    M.SALES
FROM MASTER_TABLE M
JOIN DIM_PRODUCT P
    ON M.PRODUCT_NAME = P.PRODUCT_NAME
   AND M.PRODUCT_CLASS = P.PRODUCT_CLASS
JOIN DIM_CUSTOMER C
    ON M.CUSTOMER_NAME = C.CUSTOMER_NAME
   AND M.DISTRIBUTOR = C.DISTRIBUTOR
JOIN DIM_GEOGRAPHY G
    ON M.LATITUDE = G.LATITUDE
   AND M.LONGITUDE = G.LONGITUDE
JOIN DIM_SALES_REP R
    ON M.NAME_OF_SALES_REP = R.SALES_REP_NAME
   AND M.MANAGER = R.MANAGER
JOIN DIM_CHANNEL CH
    ON M.CHANNEL = CH.CHANNEL
   AND M.SUB_CHANNEL = CH.SUB_CHANNEL;


-- to check our  main fact table is same as master table or not
SELECT
    F.TXN_ID,
    C.DISTRIBUTOR,
    C.CUSTOMER_NAME,
    G.CITY,
    G.COUNTRY,
    G.LATITUDE,
    G.LONGITUDE,
    CH.CHANNEL,
    CH.SUB_CHANNEL,
    P.PRODUCT_NAME,
    P.PRODUCT_CLASS,
    F.QUANTITY,
    F.PRICE,
    F.SALES,
    R.SALES_REP_NAME,
    R.MANAGER,
    R.SALES_TEAM,
    M.DATE
FROM FACT_SALES_TRANSACTIONS F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_GEOGRAPHY G
    ON F.GEO_ID = G.GEO_ID
JOIN DIM_CHANNEL CH
    ON F.CHANNEL_ID = CH.CHANNEL_ID
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN MASTER_TABLE M
    ON F.TXN_ID= M.TXN_ID
JOIN DIM_SALES_REP R
    ON F.SALES_REP_ID = R.SALES_REP_ID
ORDER BY TXN_ID ;



CREATE TABLE FACT_MONTHLY_PRODUCT_SALES AS
SELECT 
	P.PRODUCT_ID,
    M.DATE,
    M.SALES
FROM MONTHLY_PRODUCT_SALES M
JOIN DIM_PRODUCT P 
	ON M.PRODUCT_NAME=P.PRODUCT_NAME;
    